name: api_test_caio
description: Teste de API.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.4
  equatable: ^2.0.5
  either_dart: ^0.4.0
  dio: ^5.1.1
  get_it: ^7.4.1
  flutter_guid: ^0.3.1
  lottie: ^2.3.2
  flutter_svg: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets: 
   - assets/
   - assets/animations/
  uses-material-design: true
